services:
  app:
    build: "."
    env_file:
      - ".env.prod"
    ports:
      - "4000:4000"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:17-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 10
    volumes:
      - pgdata:/var/lib/postgresql/data

  queue:
    image: rabbitmq:4-alpine
    hostname: jobs
    ports:
      - "5672:5672"
      - "15672:15672"
    depends_on:
      app:
        condition: service_started

volumes:
  pgdata: