services:
  db:
    image: postgres:17-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
  queue:
    image: rabbitmq:4-alpine
    hostname: jobs
    ports:
      - 5672:5672
      - 15672:15672
  